//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacion_Web_Tienda_Electronicos_SA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.FACTURA = new HashSet<FACTURA>();
            this.PUNTO_ACUMULADO = new HashSet<PUNTO_ACUMULADO>();
        }
    
        public decimal ID_CLIENTE { get; set; }
        public decimal ID_ESTADO_FK { get; set; }
        public string NIT_CLIENTE { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public string APELLIDO_CLIENTE { get; set; }
        public string SEXO_CLIENTE { get; set; }
        public string TELEFONO_CLIENTE { get; set; }
        public string DIRECCION_CLIENTE { get; set; }
        public string CORREO_CLIENTE { get; set; }
        public string PASSWORD_CLIENTE { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    
        public virtual ESTADO ESTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA> FACTURA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUNTO_ACUMULADO> PUNTO_ACUMULADO { get; set; }
    }
}
